name: Automated Weather Script

on:
  schedule:
    # Runs daily at 10:00 UTC
    - cron: '0 10 * * *'
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  run-weather-script:
    runs-on: ubuntu-latest # Use an Ubuntu VM

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up the script execution environment
    - name: Ensure weather.sh is executable
      run: chmod +x weather.sh

    # Step 3: Execute the script
    - name: Run weather.sh
      run: ./weather.sh

    # Step 4: Commit and push changes
    - name: Commit and push weather data
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add data/weather/
        git commit -m "Add new weather data for $(date +"%Y-%m-%d %H:%M:%S")"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
