name: Automated Weather Script

on:
  schedule:
    # Scheduled to run daily at 10:00 AM UTC
    - cron: '0 10 * * *'
  workflow_dispatch: # Allows manual trigger for testing

jobs:
  run-weather-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Ensure weather.sh is executable
    - name: Make weather.sh executable
      run: chmod +x weather.sh

    # Step 3: Execute weather.sh script
    - name: Run weather.sh
      run: ./weather.sh

    # Step 4: Commit and push the changes
    - name: Commit and push changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add data/weather/
        git commit -m "Add new weather data for $(date +"%Y-%m-%d %H:%M:%S")"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
